### ISSUE TITLE
Driver sticks out of the car

### ISSUE THREAD

**Issue by tgomola** [Brawltendo/NFS-Rivals-Framerate-Unlocker#1]
At higher speeds, the driver starts slowly moving towards the back of the car, clipping through it, and eventually ending up being positioned behind the car. When slowing down, he returns back to his seat.

Steam version, EA App installed, MaxVariableFps set to 60, with vsync on

Frosty definitely works, because I also have Cops 2 Racers mod enabled and that works fine.

![RIVALS](https://github.com/Brawltendo/NFS-Rivals-Framerate-Unlocker/assets/30185271/f7819eb5-e276-4cdb-9d20-7c30e1903cd2)

**Comment by Brawltendo** [comment]
Just released v1.0.1, this should be fixed now on the Steam version.
